### ISSUE TITLE
Crash when loading into a game with the mod in 1.1.87

### ISSUE THREAD

**Issue by kepler-gray** [DaveMcW/itemcam#1]
The mod Item Cam (0.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event itemcam::on_configuration_changed
Only custom shortcut prototypes with the action type "lua" can be used. For all others there are specific functions/properties.
stack traceback:
	[C]: in function 'set_shortcut_toggled'
	__itemcam__/control.lua:923: in function 'exit_itemcam'
	__itemcam__/control.lua:88: in function <__itemcam__/control.lua:86>

**Comment by DaveMcW** [comment]
I can't reproduce this. It seems like a mod conflict, because my shortcut prototypes already have the action type "lua".

Does it still crash if you disable all mods except Item Cam?

**Comment by kepler-gray** [comment]
> I can't reproduce this. It seems like a mod conflict, because my shortcut prototypes already have the action type "lua".
> 
> Does it still crash if you disable all mods except Item Cam?

Interesting, disabling [Shortcuts for 1.1](https://mods.factorio.com/mod/Shortcuts-ick) fixed it. Wish I could continue to use both, not sure if that would be on you or on them to fix.

**Comment by DaveMcW** [comment]
[Shortcuts for 1.1](https://mods.factorio.com/mod/Shortcuts-ick) is destroying all "lua" shortcuts by overwriting them with "spawn-item" shortcuts.

The only fix I could do is do a dependency arms race to overwrite it back. But I don't care enough to support compatibility with such a buggy mod.
